version: '3'
services:
  server:
    build:
      context: ./server
    restart: always
    command: npm run start:prod
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - ./data/public/static/upload:/code/public/static/upload
    environment:
       DATABASE_URL: mysql://lzc:bs32g1038@db:3306/jixialunbi
       MEILI_SEARCH_CLIENT_HOST: http://meilisearch:7700
       MEILI_SEARCH_CLIENT_API_KEY: jixialunbi
    networks:
      - jixialunbi-network
  web:
    build:
      context: ./web
    restart: always
    command: npm run start
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - jixialunbi-network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: jixialunbi
      MYSQL_USER: root
      MYSQL_PASSWORD: bs32g1038
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - jixialunbi-network
  meilisearch:
    image: getmeili/meilisearch:v0.28
    restart: always
    environment:
      MEILI_MASTER_KEY: jixialunbi
    volumes:
      - ../data/meili_data:/meili_data
    ports:
      - 7700:7700
    networks:
      - jixialunbi-network
networks:
  jixialunbi-network:
      driver: bridge