version: '3'
services:
  server:
    image: ghcr.io/bs32g1038/jixialunbi-server:v1
    restart: always
    depends_on:
      - db
    ports:
      - 4000:8080
    volumes:
      - ./data/public/static/upload:/code/public/static/upload
    environment:
       DATABASE_URL: mysql://lzc:bs32g1038@db:3306/jixialunbi
    networks:
      - jixialunbi-network
  web:
    image: ghcr.io/bs32g1038/jixialunbi-web:v1
    restart: always
    command: npm run start
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - jixialunbi-network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: jixialunbi
      MYSQL_USER: root
      MYSQL_PASSWORD: bs32g1038
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - jixialunbi-network
networks:
  jixialunbi-network:
      driver: bridge