version: '3'
services:
  server:
    image: ghcr.io/bs32g1038/jixialunbi-server:v1
    restart: always
    depends_on:
      - db
    environment:
       DB_NAME: jixialunbi
       DB_USERNAME: lzc
       DB_PASSWORD: bs32g1038
       JWT_SECRET: appSecretKey
       EMAIL_PASS: XXX
    network_mode: host
    volumes:
      - ./data/static:/app/static
  web:
    image: ghcr.io/bs32g1038/jixialunbi-web:v1
    restart: always
    command: npm run start
    depends_on:
      - server
    network_mode: host
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: jixialunbi
      MYSQL_USER: lzc
      MYSQL_PASSWORD: bs32g1038
      MYSQL_ROOT_PASSWORD: ubuntu
    volumes:
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./data/mysql/data:/var/lib/mysql
    network_mode: host